# Generated by Django 4.2.11 on 2024-04-13 16:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polygon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polygonmodel",
            name="intersects_antimeridian",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Признак пересечения антимеридиана"
            ),
        ),
        migrations.AlterField(
            model_name="polygonmodel",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="polygonmodel",
            name="polygon",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326, verbose_name="Координаты полигона"
            ),
        ),
    ]
