version: '3'

services:
  db:
    image: postgis/postgis
    restart: always
#    env_file: .env
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=gis
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgis:/var/lib/postgresql/data


  app:
    build: .
    env_file: .env
    tty: true
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - db


volumes:
  pg_data: